
# # LLM 설정
# DEFAULT_MODEL = "deepseek-chat"
# DEFAULT_TEMPERATURE = 0.1

# ADVANCED_MODEL = "deepseek-chat"
# ADVANCED_TEMPERATURE = 0.1

# # 시스템 설정
# MAX_ATTEMPTS = 3
# DEFAULT_LANGUAGE = "chinese"


# LLM 설정
DEFAULT_MODEL = "gpt-4.1-mini"
DEFAULT_TEMPERATURE = 0.1

ADVANCED_MODEL = "gpt-4.1-mini"
ADVANCED_TEMPERATURE = 0.1

# 시스템 설정
MAX_ATTEMPTS = 3
DEFAULT_LANGUAGE = "chinese"