"""
공통 템플릿 패키지

이 패키지는 공통으로 사용되는 템플릿을 제공합니다.
"""

from .json_templates import (
    PLANNER_CALCULATION_JSON_TEMPLATE,
    PLANNER_NO_CALCULATION_JSON_TEMPLATE,
    COMMAND_SELECTION_TEMPLATE,
    COMMAND_GENERATION_TEMPLATE,
    VALIDATION_JSON_TEMPLATE,
    COMMAND_REGENERATION_JSON_TEMPLATE,
    MANAGER_JSON_TEMPLATE,
    TRIANGLE_JSON_TEMPLATE,
    ANGLE_JSON_TEMPLATE,
    COORDINATE_JSON_TEMPLATE,
    LENGTH_JSON_TEMPLATE,
    AREA_JSON_TEMPLATE,
    CIRCLE_JSON_TEMPLATE,
    MERGER_JSON_TEMPLATE
)

__all__ = [
    "PLANNER_CALCULATION_JSON_TEMPLATE",
    "PLANNER_NO_CALCULATION_JSON_TEMPLATE",
    "COMMAND_SELECTION_TEMPLATE",
    "COMMAND_GENERATION_TEMPLATE",
    "VALIDATION_JSON_TEMPLATE",
    "COMMAND_REGENERATION_JSON_TEMPLATE",
    # Calculation JSON Template ------------------------------------------------------------
    "MANAGER_JSON_TEMPLATE",
    "TRIANGLE_JSON_TEMPLATE",
    "ANGLE_JSON_TEMPLATE",
    "COORDINATE_JSON_TEMPLATE",
    "LENGTH_JSON_TEMPLATE",
    "AREA_JSON_TEMPLATE",
    "CIRCLE_JSON_TEMPLATE",
    "MERGER_JSON_TEMPLATE"
]
